import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../utils/api'
import { useTheme } from '../contexts/ThemeContext'

const CompanyRegistration = () => {
  const navigate = useNavigate()
  const theme = useTheme()
  const [formData, setFormData] = useState({
    name: '',
    company_email: '',
    website: '',
    industry: '',
    size: '',
    description: '',
    auth0_org_id: '' // This will be generated by the backend
  })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState(false)

  const companySizes = [
    { value: 'startup', label: 'Startup (1-10 employees)' },
    { value: 'small', label: 'Small (11-50 employees)' },
    { value: 'medium', label: 'Medium (51-200 employees)' },
    { value: 'large', label: 'Large (201-1000 employees)' },
    { value: 'enterprise', label: 'Enterprise (1000+ employees)' }
  ]

  const handleChange = (e) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))
  }

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    setError('')

    try {
      // Remove auth0_org_id from form data as it's generated by backend
      const { auth0_org_id, ...submitData } = formData
      const response = await api.registerCompany(submitData)

      setSuccess(true)
      // Redirect to login after successful registration
      setTimeout(() => {
        navigate('/login')
      }, 2000)
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message)
      } else {
        setError('An unexpected error occurred. Please try again.')
      }
    } finally {
      setLoading(false)
    }
  }

  if (success) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <div className="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
            <div className="text-center">
              <div className="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-green-100">
                <svg className="h-6 w-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <h2 className="mt-4 text-2xl font-bold text-gray-900">Registration Successful!</h2>
              <p className="mt-2 text-gray-600">
                Your company has been registered successfully. You'll be redirected to login shortly.
              </p>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className={`min-h-screen flex flex-col justify-center py-12 sm:px-6 lg:px-8 transition-colors duration-300 ${theme.bg.primary}`}>
      <div className="sm:mx-auto sm:w-full sm:max-w-md">
        <Link to="/" className="flex justify-center">
          <h1 className={`text-3xl font-bold ${theme.text.gradient}`}>🚀 Kuuza AI</h1>
        </Link>
        <h2 className={`mt-6 text-center text-3xl font-bold ${theme.text.primary}`}>
          Register Your Company
        </h2>
        <p className={`mt-2 text-center text-sm ${theme.text.secondary}`}>
          Already have an account?{' '}
          <Link to="/login" className={`font-medium ${theme.text.accent} ${theme.hover.link}`}>
            Sign in here
          </Link>
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
        <div className={`${theme.bg.card} py-8 px-4 sm:rounded-lg sm:px-10`}>
          <form className="space-y-6" onSubmit={handleSubmit}>
            {error && (
              <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
                {error}
              </div>
            )}

            <div>
              <label htmlFor="name" className={`block text-sm font-medium ${theme.text.primary}`}>
                Company Name *
              </label>
              <div className="mt-1">
                <input
                  id="name"
                  name="name"
                  type="text"
                  required
                  value={formData.name}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white placeholder-gray-400 focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500'}`}
                  placeholder="Enter your company name"
                />
              </div>
            </div>

            <div>
              <label htmlFor="website" className={`block text-sm font-medium ${theme.text.primary}`}>
                Website
              </label>
              <div className="mt-1">
                <input
                  id="website"
                  name="website"
                  type="url"
                  value={formData.website}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white placeholder-gray-400 focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500'}`}
                  placeholder="https://yourcompany.com"
                />
              </div>
            </div>

            <div>
              <label htmlFor="email" className={`block text-sm font-medium ${theme.text.primary}`}>
                Email
              </label>
              <div className="mt-1">
                <input
                  id="email"
                  name="company_email"
                  type="email"
                  value={formData.company_email}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white placeholder-gray-400 focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500'}`}
                  placeholder="company@example.com" required
                />
              </div>
            </div>

            <div>
              <label htmlFor="industry" className={`block text-sm font-medium ${theme.text.primary}`}>
                Industry
              </label>
              <div className="mt-1">
                <input
                  id="industry"
                  name="industry"
                  type="text"
                  value={formData.industry}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white placeholder-gray-400 focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500'}`}
                  placeholder="e.g., Technology, Healthcare, Finance"
                />
              </div>
            </div>

            <div>
              <label htmlFor="size" className={`block text-sm font-medium ${theme.text.primary}`}>
                Company Size
              </label>
              <div className="mt-1">
                <select
                  id="size"
                  name="size"
                  value={formData.size}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 focus:ring-blue-500 focus:border-blue-500'}`}
                >
                  <option value="">Select company size</option>
                  {companySizes.map(size => (
                    <option key={size.value} value={size.value}>
                      {size.label}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div>
              <label htmlFor="description" className={`block text-sm font-medium ${theme.text.primary}`}>
                Description
              </label>
              <div className="mt-1">
                <textarea
                  id="description"
                  name="description"
                  rows={3}
                  value={formData.description}
                  onChange={handleChange}
                  className={`w-full px-3 py-2 border rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 transition-colors ${theme.isDark ? 'bg-white/10 border-white/20 text-white placeholder-gray-400 focus:ring-cyan-500 focus:border-cyan-500' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500 focus:ring-blue-500 focus:border-blue-500'}`}
                  placeholder="Brief description of your company"
                />
              </div>
            </div>

            <div>
              <button
                type="submit"
                disabled={loading}
                className={`w-full ${theme.button.primary} py-3 px-4 rounded-md font-semibold transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed transform hover:scale-105`}
              >
                {loading ? 'Registering...' : 'Register Company'}
              </button>
            </div>
          </form>

          <div className="mt-6">
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className={`w-full border-t ${theme.isDark ? 'border-white/20' : 'border-gray-300'}`} />
              </div>
              <div className="relative flex justify-center text-sm">
                <span className={`px-2 ${theme.isDark ? 'bg-gray-900' : 'bg-white'} ${theme.text.muted}`}>Or</span>
              </div>
            </div>

            <div className="mt-6">
              <Link
                to="/"
                className={`w-full flex justify-center py-2 px-4 rounded-md shadow-sm text-sm font-medium transition-colors ${theme.button.secondary}`}
              >
                Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default CompanyRegistration
